### PR TITLE
EarthWorks v2.1.001 Branch

### PR DESCRIPTION
**Pull request by gdicker1**
Incorporate PRs and fixes in externals

### CODE REVIEW

**Comment by gdicker1** [comment]
Issue Fixes:
- Part of https://github.com/EarthWorksOrg/EarthWorks/issues/31

Relevant PRs in externals:
- https://github.com/EarthWorksOrg/mpas-framework/pull/6
- https://github.com/EarthWorksOrg/mpas-seaice/pull/7

**Comment by dazlich** [comment]
I tested the 32L 120km fully-coupled model. Builds and runs for intel, gnu, and nvhpc compilers on cpu. 

Has a build issue with intel-oneapi:
ERROR: Command: '/glade/u/home/dazlich/ewv2.1/post_relv21/components/cam/bld/configure -s -fc_type intel-oneapi -dyn mpas -hgrid mpasa120 -cpl nuopc -usr_src /glade/derecho/scratch/dazlich/frametest.intel-oneapi/SourceMods/src.cam -spmd -nosmp -ocn mpaso -dyn mpas -nlev=32 -mpas_libdir /glade/derecho/scratch/dazlich/frametest.intel-oneapi/bld/atm/obj/mpas' failed with error 'ERROR: intel-oneapi is not a valid value for parameter fc_type: valid values are cray,pgi,intel,gnu,pathscale,ibm,nag,nvhpc,pgi-gpu,nvhpc-gpu' from dir '/glade/derecho/scratch/dazlich/frametest.intel-oneapi/Buildconf/camconf'

**Comment by gdicker1** [comment]
> I tested the 32L 120km fully-coupled model. Builds and runs for intel, gnu, and nvhpc compilers on cpu.
> 
> Has a build issue with intel-oneapi: ERROR: Command: ...

Thanks for testing, @dazlich!

It looks like the issue comes from the CAM side in the bld/config_files
/definition.xml file: [Lines 224-227](https://github.com/EarthWorksOrg/CAM/blob/04bbb089b65aa452a2ae3344cf7ac7c69254e228/bld/config_files/definition.xml#L224-L227) which doesn't include `intel-oneapi`. We've been able to build/run with this compiler before, right?

```
<entry id="fc_type" valid_values="cray,pgi,intel,gnu,pathscale,ibm,nag,nvhpc,pgi-gpu,nvhpc-gpu" value="">
Type of Fortran compiler.  Used when -fc specifies a generic wrapper script
such as mpif90 or ftn.
</entry>
```

**Comment by dazlich** [comment]
I’ve had successful tests with oneapi as recently as February 20 with the v2.1 release.

On Mar 6, 2024, at 2:37 PM, G. Dylan Dickerson ***@***.***> wrote:


** Caution: EXTERNAL Sender **


I tested the 32L 120km fully-coupled model. Builds and runs for intel, gnu, and nvhpc compilers on cpu.

Has a build issue with intel-oneapi: ERROR: Command: ...

Thanks for testing, @dazlich<https://github.com/dazlich>!

It looks like the issue comes from the CAM side in the bld/config_files
/definition.xml file: Lines 224-227<https://github.com/EarthWorksOrg/CAM/blob/04bbb089b65aa452a2ae3344cf7ac7c69254e228/bld/config_files/definition.xml#L224-L227> which doesn't include intel-oneapi. We've been able to build/run with this compiler before, right?

<entry id="fc_type" valid_values="cray,pgi,intel,gnu,pathscale,ibm,nag,nvhpc,pgi-gpu,nvhpc-gpu" value="">
Type of Fortran compiler.  Used when -fc specifies a generic wrapper script
such as mpif90 or ftn.
</entry>

**Comment by gdicker1** [comment]
Edited [this comment above](https://github.com/EarthWorksOrg/EarthWorks/pull/32#issuecomment-1957809841) to change the MPAS-SI PR from [EWOrg/MPAS-SI #7](https://github.com/EarthWorksOrg/mpas-seaice/pull/7) to [EWOrg/MPAS-SI #8](https://github.com/EarthWorksOrg/mpas-seaice/pull/8)

**Comment by gdicker1** [comment]
**NOTE:** this PR now needs to add #35 to the issues and [EWOrg/CAM #15](https://github.com/EarthWorksOrg/CAM/pull/15) to the PRs

**Comment by gdicker1** [comment]
Edited [this comment above](https://github.com/EarthWorksOrg/EarthWorks/pull/32#issuecomment-1957809841) to add [#35](https://github.com/EarthWorksOrg/EarthWorks/issues/35)and [EWOrg/CAM #15](https://github.com/EarthWorksOrg/CAM/pull/15)

**Comment by gdicker1** [comment]
> ...
> * Fixes [EarthWorks porting to Perlmutter #33](https://github.com/EarthWorksOrg/EarthWorks/issues/33) by modifying the `perlmutter_ew_debug` machine entry in EarthWorksOrg/ccs_configs_cesm
> ...
> * [Fix case.setup on Perlmutter for perlmutter_ew_debug ccs_config_cesm#17](https://github.com/EarthWorksOrg/ccs_config_cesm/pull/17)

Dropping references to Perlmutter from [this comment](https://github.com/EarthWorksOrg/EarthWorks/pull/32#issuecomment-1957809841) according to discussion and commit https://github.com/EarthWorksOrg/EarthWorks/pull/32/commits/8558c58168b8e4b9a254e1c30c350beb44fbc7a5

**Pull request merged**
