### PR TITLE
Bring in changes cam_dev physics and to use gh1 machine

### LINKED ISSUE #46: Update EW MPAS-A to v8+ version to use new input data files
The current version of MPAS-A in EarthWorks lags behind what is used in the cam_development branch. [EWOrg/MPAS-Model](https://github.com/EarthWorksOrg/MPAS-Model) is a v7.x OpenACC version while what ESCOMP/CAM uses is based on a v8.0.1 hash ([b8c33daa in MPAS-Dev/MPAS-Model](https://github.com/MPAS-Dev/MPAS-Model/commit/b8c33daa4b124f116b0ba1b1386968c4c15b42e4)). This means that EWOrg/MPAS-Model is missing code to use the `cell_gradient_coef_{xy}` fields/variables and runs fail when CAM tries to direct MPAS-A to read those fields.

This impacts and/or is impacted by:
- [EWOrg/CAM PR #16](https://github.com/EarthWorksOrg/CAM/pull/16)

When built with `DEBUG=true`, you will see lines like below at the end of the file. Otherwise the "`Warning: *`" statements won't be present, and the run will just die.
```
# skipped content...
 Allocating fields ...
  4 MB allocated for fields on this task
  567 MB total allocated for fields across all tasks
  ----- done allocating fields -----   
     
WARNING: Error: Field cell_gradient_coef_x not found in pool.
WARNING: Error: Field cell_gradient_coef_y not found in pool.
```

### PR DESCRIPTION
**Pull request by gdicker1**
See Sub-PRs: [EWOrg/ccs_config_cesm #20](https://github.com/EarthWorksOrg/ccs_config_cesm/pull/20), [EWOrg/CAM #16](https://github.com/EarthWorksOrg/CAM/pull/16) -> sub PR [EWOrg/MPAS-Model #3](https://github.com/EarthWorksOrg/MPAS-Model/pull/3)

These changes are best tested by attempting a run of the "F2000dev" compset (similar instructions to running F2000climo).

Closes #46

### CODE REVIEW

**Review by dazlich — APPROVED** [review]
Looks good! I was able to run a 120km case.

**Comment by dazlich** [comment]
I tried it in a coupled run (compset=2000_CAM%DEV_CLM50%SP_MPASSI_MPASO_MOSART_SGLC_SWAV) at 120km and it fails.

dec1784.hsn.de.hpc.ucar.edu 161: forrtl: severe (71): integer divide by zero
dec1784.hsn.de.hpc.ucar.edu 161: Image              PC                Routine            Line        Source
dec1784.hsn.de.hpc.ucar.edu 161: libpthread-2.31.s  00001461D27E48C0  Unknown               Unknown  Unknown
dec1784.hsn.de.hpc.ucar.edu 161: cesm.exe           0000000000735F60  radiation_mp_radi         299  radiation.F90
dec1784.hsn.de.hpc.ucar.edu 161: cesm.exe           000000000072C4A6  radiation_mp_radi         891  radiation.F90
dec1784.hsn.de.hpc.ucar.edu 161: cesm.exe           00000000006E4E05  physpkg_mp_tphysb        2879  physpkg.F90
dec1784.hsn.de.hpc.ucar.edu 161: cesm.exe           00000000006D686D  physpkg_mp_phys_r        1188  physpkg.F90
dec1784.hsn.de.hpc.ucar.edu 161: cesm.exe           00000000005970A6  cam_comp_mp_cam_r         260  cam_comp.F90
dec1784.hsn.de.hpc.ucar.edu 161: cesm.exe           000000000057E629  atm_comp_nuopc_mp         909  atm_comp_nuopc.F90

**Comment by dazlich** [comment]
More detail:
This is the line:
      radiation_do = nstep == 0  .or.  iradsw == 1                     &
                    .or. (mod(nstep-1,iradsw) == 0  .and.  nstep /= 1) &
                    .or. nstep <= irad_always

It appears iradsw is set to 0, causing the divide by zero in the mod()

**Comment by dazlich** [comment]
I think with recent changes to some of the time step and coupling defaults I had some old values in my script. CHAOS2000 now runs with the -phys cam_dev specified in CAM_CONFIG_OPTS.

I am happy again and this PR looks good.

**Comment by gdicker1** [comment]
> I think with recent changes to some of the time step and coupling defaults I had some old values in my script. CHAOS2000 now runs with the -phys cam_dev specified in CAM_CONFIG_OPTS.
> 
> I am happy again and this PR looks good.

Thanks for checking this and providing the context. They might be some good hints later down the line!

**Comment by gdicker1** [comment]
To make some GH1 testing easier, I'm going to move ahead and merge these changes. If the GH1 entry has issues, we can fix them in a separate PR.

**Pull request merged**
