### PR TITLE
Add initial LICENSE

### PR DESCRIPTION
**Pull request by gdicker1**
Provides initial legal information for the publication and use of the EarthWorks Modeling System.

### CODE REVIEW

**Comment by gdicker1** [comment]
Please let me know what you think of this @areanddee @sherimickelson. I made some formatting edits so that it will read well as a plain text document. Some of these include:

- Limiting to lines to 80 columns
- Editing/adjusting the table of sub-licenses
- Converting the footnotes to be more like endnotes in a Markdown style.

**Review by sherimickelson — APPROVED** [review]
Looks great!  Thanks @gdicker1

**Comment by areanddee** [comment]
Looks great. Thanks for reformatting.

**Comment by areanddee** [comment]
> Provides initial legal information for the publication and use of the EarthWorks Modeling System.

**Pull request closed without merging**
