### PR TITLE
Checkout update/ocean branches

### PR DESCRIPTION
**Pull request by dazlich**
modify to checkout the update/ocean branches of
CMEPS
mpas-ocean
mpas-seaice
mpas-framework

This is part of a package of PRs for branches named update/ocean:
EarthWorksOrg /mpas-ocean PR [#15](https://github.com/EarthWorksOrg/mpas-ocean/pull/15)
EarthWorksOrg /mpas-seaice PR [#17](https://github.com/EarthWorksOrg/mpas-seaice/pull/17)
EarthWorksOrg /mpas-framework PR [#10](https://github.com/EarthWorksOrg/mpas-framework/pull/10)
EarthWorksOrg /CMEPS PR [#12](https://github.com/EarthWorksOrg/CMEPS/pull/12)
EarthWorksOrg/EarthWorks PR [#75](https://github.com/EarthWorksOrg/EarthWorks/pull/75) (incorporates above)

### CODE REVIEW

**Comment by gdicker1** [comment]
Note: As near as I can figure, the branch '[vanroekel/ocean/update-nonhydro-2-15-2023](https://github.com/vanroekel/E3SM/tree/vanroekel/ocean/update-nonhydro-2-15-2023)' is based on tag 'v2.1.0' from [E3SM-Project/E3SM](https://github.com/E3SM-Project/E3SM).

Since we are trying to track the last upstream version using out EarthWorks tags, I'm planning for the last lines for mpas-framework, mpas-ocean, and mpas-seaice tags to now be:

> Last changes from upstream 'E3SM-Project/E3SM' roughly tag:'v2.1.0'

I'm adding "roughly" since the last E3SM tag in the 'vanroekel...' branch is "`v2.1.0`" but git-describe puts it as "`v2.1.0-162-gfbff87e614`". (i.e. there are 162 changes in this branch since v2.1.0.)

**Comment by gdicker1** [comment]
I've run the ew-pr tests using the results of #73 as the baseline with the following results:

- FHS94, FKESSLER, and FHS94 tests all passed
    - all of these tests use mpasa120_mpasa120 grids, and are atm-only. It's a good sign that these simply passed.
- CHAOS2000dev and FullyCoupled tests all had differences when comparing against the baseline.
    - 252 of 365 fields compared had differences. This is too many to closely parse, but I'm pretty sure these are fields that could reasonably be affected by this update for MPAS-Ocean
- F2000climoEW tests **_FAILED_**

F2000climoEW seems to be our only case that uses the prescribed seaice setting. Most log files from the run contain very little information.

End of cesm.log

>  dec2301.hsn.de.hpc.ucar.edu 0:  (t_initf)       profile_papi_enable=       F
>  dec2301.hsn.de.hpc.ucar.edu 0:  Attribute logunit not set for ICE
>  dec2301.hsn.de.hpc.ucar.edu 0:  ICE: PIO numiotasks=            1
>  dec2301.hsn.de.hpc.ucar.edu 0:  ICE: PIO stride=          128
>  dec2301.hsn.de.hpc.ucar.edu 0:  ICE: PIO rearranger=            2
>  dec2301.hsn.de.hpc.ucar.edu 0:  ICE: PIO root=            1
>  dec2301.hsn.de.hpc.ucar.edu 8: MPICH Notice [Rank 8] [job id d6780e88-9da6-4634-a90c-6da37bd685d6] [Tue Oct 15 19:33:31 2024] [dec2301] - Abort(0) (rank 8 in comm  0): application called MPI_Abort(MPI_COMM_WORLD, 0) - process 8
>  dec2301.hsn.de.hpc.ucar.edu 8:
>  dec2301.hsn.de.hpc.ucar.edu 8: aborting job:
>  dec2301.hsn.de.hpc.ucar.edu 8: application called MPI_Abort(MPI_COMM_WORLD, 0) - process 8
> ... lines repeat for each aborted process ...

There is also a fort.99 file which contains helpful text

> === Beginning ice_init_nuopc: rank=     0
> ----------------------------------------------------------------------
> Beginning MPAS-seaice Output Log File for task       0 of     128
>     Opened at 2024/10/15 19:33:31
> ----------------------------------------------------------------------
> 
>  Reading namelist from file mpassi_in
> CRITICAL ERROR: Error while reading namelist record prescribed_ice.
>  
>  -----------------------------------------
>  Total log messages printed:
>     Output messages =                    1
>     Warning messages =                   0
>     Error messages =                     0
>     Critical error messages =            1
>  -----------------------------------------
>  Logging complete.  Closing file at 2024/10/15 19:33:31

**Comment by gdicker1** [comment]
@dazlich, could you take a look at the prescribed seaice with these changes? As I note in [this comment above](https://github.com/EarthWorksOrg/EarthWorks/pull/75#issuecomment-2418303186), it doesn't seem to be working out-of-the-box. There's at least a namelist change that is needed if we want to keep this functionality.

**Comment by dazlich** [comment]
I’ll take a look at the seaice prescribed mode.


On Oct 16, 2024, at 7:31 PM, G. Dylan Dickerson ***@***.***> wrote:

﻿

** Caution: EXTERNAL Sender **

@dazlich<https://github.com/dazlich>, could you take a look at the prescribed seaice with these changes? As I note in this comment above<https://github.com/EarthWorksOrg/EarthWorks/pull/75#issuecomment-2418303186>, it doesn't seem to be working out-of-the-box. There's at least a namelist change that is needed if we want to keep this functionality.

**Comment by dazlich** [comment]
@gdicker1  Seaice prescribed mode is now fixed. I had to restore a few lines in mpas-seaice/src/Registry.xml.

**Review by gdicker1 — APPROVED** [review]
Now, F2000climoEW test runs to completion. It also has differences in the namelist and compared to the baseline (193 of 324 fields compared), which I think would be reasonable.

These changes make sense and are approved! I'll add a final commit tomorrow morning to use tags in .gitmodules and merge all the PRs.

**Pull request merged**
