### PR TITLE
Update externals based on ESCOMP/CESM tag 'cesm3_0_beta03'

### PR DESCRIPTION
**Pull request by gdicker1**
This PR catches up to the current development in ESCOMP/CESM. This includes updating some externals (a.k.a. submodules) through PRs, updating git-fleximod, syncing the cime_config folder, and other miscellaneous changes to match CESM.

### CODE REVIEW

**Comment by gdicker1** [comment]
Sub PRs:
- https://github.com/EarthWorksOrg/CMEPS/pull/13
- https://github.com/EarthWorksOrg/cime/pull/14
- https://github.com/EarthWorksOrg/ccs_config_cesm/pull/28
- https://github.com/EarthWorksOrg/CAM/pull/34

**Comment by sherimickelson** [comment]
Thanks @gdicker1 !  Have you tested this with the nvhpc compiler (on CPU or GPU)?  I'm having difficulties building the cesm3_0_beta03 tag with nvphc.  I'm seeing a "rc=2" error while building the atm library.  I see this with version 24.3 and 24.9.  I'm just wondering if you've seen something similar with the EarthWorks code?

**Comment by gdicker1** [comment]
@sherimickelson I haven't, but I was just about to kick off the testing for this PR. I'll watch out for this and reply with what I see. I don't recall seeing this for the cesm3_0_beta02 update.

**Comment by gdicker1** [comment]
@sherimickelson, I didn't have any problems building EarthWorks tests (using nvhpc/24.3 stack on Derecho). I could try to take a peak if you send me a path to your testcase and/or sandbox.

Also I'm looking into namelist differences and differences in the baseline vs test results before I'm sure of this PR.

**Comment by sherimickelson** [comment]
Thanks for double-checking, @gdicker1. I wonder if something in my environment is causing this.  
Could we update to NVHPC 24.9?  It seems to fix the restart problem when running with the mpas-a dycore.

**Comment by gdicker1** [comment]
> Thanks for double-checking, @gdicker1. I wonder if something in my environment is causing this. Could we update to NVHPC 24.9? It seems to fix the restart problem when running with the mpas-a dycore.

@sherimickelson yes, I'll get right on modifying EarthWorksOrg/ccs_configs_cesm. I'm thinking it will be a separate PR so I can also add some restart tests.

**Comment by gdicker1** [comment]
Results from testing with results from #75 as baseline:

- FHS94 tests and the FKESSLER test only had namelist differences
    - This isn't surprising, some changes were around deposition files. Also a change was made from `64bit_offset` to `64bit_data` for the `pio_netcdf_format`.
- QPC6 test had namelist and answer differences
    - I would suspect this is either due to changes to deposition files or inclusion of this new `dust_emis_inparm`.
    - 58 of 154 fields compared had diffs. Seems reasonable.
- CHAOS2000dev test had namelist and answer differences
    - Again seems reasonable given the changes. Also using a different fsurdat file
    - 261 of 365 fields compared had diffs.
- F2000climoEW tests had namelist and answer differences
    - Similar to CHAOS2000dev
    - 202 of 324 fields compared had diffs
- FullyCoupledEW
    - 242 of 331 fields compared had diffs.

As I said, the changes seem reasonable for how different the namelists are and changes around CTSM files. I plan to push the merged branches soon.

**Pull request merged**
