### PR TITLE
Incorporate mpas-frwk2.1.003 and mpas-seaice2.1.003 tags

### PR DESCRIPTION
**Pull request by gdicker1**
Bring in changes from EWOrg/mpas-framework PR#8 and EWOrg/mpas-seaice PR#10.

Links:
- https://github.com/EarthWorksOrg/mpas-framework/pull/8
- https://github.com/EarthWorksOrg/mpas-seaice/pull/10

### CODE REVIEW

**Comment by gdicker1** [comment]
@dazlich could you please spot check that the correct changes are fetched with this branch?

**Comment by dazlich** [comment]
I’ll be back in town Monday and will check it out first thing.

Sent from my iPhone

On May 3, 2024, at 1:25 PM, G. Dylan Dickerson ***@***.***> wrote:

﻿

** Caution: EXTERNAL Sender **

@dazlich<https://github.com/dazlich> could you please spot check that the correct changes are fetched with this branch?

**Comment by gdicker1** [comment]
> I’ll be back in town Monday and will check it out first thing.

No worries! 

I expanded the number of reviewers. If anyone could make sure the code fetches and goes through `checkout_externals` correctly, I think this can be merged!

**Review by dazlich — APPROVED** [review]
Ok, I see the changes I intended checked out, and a test (120km,32L,fully-coupled) with the gnu compiler compiles and runs. Looks good to go.

**Pull request merged**
